import { ResourceNotFoundException } from "#errors";

export default async function getOne{{UpperCaseName}}UseCase({ {{UpperCaseName}}, logger }, id) {
  logger.debug(`Get one {{UpperCaseName}} with id: ${id}`);

  const maybe{{UpperCaseName}} = await {{UpperCaseName}}.findOne({
    where: {
      id,
    },
    raw: true,
  });

  if (!maybe{{UpperCaseName}}) return new ResourceNotFoundException(`{{UpperCaseName}} with id ${id} not found`);

  return maybe{{UpperCaseName}};
}
